"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(nome, padrao=False):
    return os.environ.get(nome, str(padrao)).lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina SECRET_KEY no ambiente.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-&gz67s92#_+r(gcjodu#8n00c2rqmo1g@ury_-%wnr%x7!xx$3',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', True)

# Hosts permitidos (separados por vírgula no ambiente). Ex.: "meusite.com,www.meusite.com"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Origens confiáveis para CSRF (necessário atrás de proxy/HTTPS). Ex.: "https://meusite.com"
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# No Render, o host público é injetado automaticamente — inclui sem precisar configurar.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    if _render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_render_host)
    _render_origin = f'https://{_render_host}'
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

# Nome do escritório exibido na interface (login, menu lateral, título).
ESCRITORIO_NOME = os.environ.get('ESCRITORIO_NOME', 'Tiago Neves Advocacia Empresarial')

# Fila de tarefas assíncronas (OCR -> indexação no upload de documentos).
# Broker via banco de dados (ORM) — não exige Redis. Rode `manage.py qcluster`.
Q_CLUSTER = {
    'name': 'juriai',
    'workers': int(os.environ.get('Q_WORKERS', '2')),
    'timeout': 600,
    'retry': 1200,
    'orm': 'default',
    'save_limit': 250,
    'catch_up': False,
    # Q_SYNC=True processa as tarefas no próprio processo (sem worker separado).
    # Útil no plano gratuito do Render, que não permite um serviço de worker.
    'sync': _env_bool('Q_SYNC', False),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'usuarios',
    'ia',
    'gestao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestao.context_processors.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Ordem de prioridade:
#   1) DATABASE_URL  (formato usado pelo Render, Heroku, etc.)
#   2) POSTGRES_DB   (variáveis separadas)
#   3) SQLite        (desenvolvimento)
import urllib.parse as _urlparse

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    _u = _urlparse.urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _u.path.lstrip('/'),
            'USER': _urlparse.unquote(_u.username or ''),
            'PASSWORD': _urlparse.unquote(_u.password or ''),
            'HOST': _u.hostname or '',
            'PORT': str(_u.port or '5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'prefer')},
        }
    }
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 600,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

import os

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'templates/static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# WhiteNoise: compressão + cache dos arquivos estáticos servidos pelo app.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de segurança aplicadas apenas em produção (DEBUG=False).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


from django.contrib.messages import constants

MESSAGE_TAGS = {
    constants.SUCCESS: 'bg-green-50 text-green-700',
    constants.ERROR: 'bg-red-50 text-red-700'
}

# Autenticação / redirecionamentos
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ---------------------------------------------------------------------------
# Configuração da camada de IA (OCR/RAG)
#
# Geração das respostas: Claude (Anthropic) -> defina ANTHROPIC_API_KEY.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
IA_CLAUDE_MODEL = os.environ.get('IA_CLAUDE_MODEL', 'claude-opus-4-8')

# Embeddings (busca vetorial). A Anthropic não oferece embeddings, então o
# backend é configurável. Padrão 'local' (transformers, sem chave de API).
#   IA_EMBEDDING_BACKEND = 'local' | 'openai' | 'voyage'
IA_EMBEDDING_BACKEND = os.environ.get('IA_EMBEDDING_BACKEND', 'local')
IA_EMBEDDING_MODEL_LOCAL = os.environ.get(
    'IA_EMBEDDING_MODEL_LOCAL', 'sentence-transformers/all-MiniLM-L6-v2'
)
# Backend 'openai'
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
IA_EMBEDDING_MODEL = os.environ.get('IA_EMBEDDING_MODEL', 'text-embedding-3-small')
# Backend 'voyage'
VOYAGE_API_KEY = os.environ.get('VOYAGE_API_KEY', '')
IA_VOYAGE_MODEL = os.environ.get('IA_VOYAGE_MODEL', 'voyage-3')

LANCEDB_PATH = os.environ.get('LANCEDB_PATH', os.path.join(BASE_DIR, 'lancedb'))
