# Generated by Django 5.2.15 on 2026-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_documentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="CPF / CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
