# Generated by Django 5.2.15 on 2026-06-28 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0003_cliente_cidade_cliente_cpf_cnpj_cliente_criado_em_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome completo"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("ADVOGADO", "Advogado(a)"),
                            ("ESTAGIARIO", "Estagiário(a)"),
                            ("SECRETARIA", "Secretária(o)"),
                            ("FINANCEIRO", "Financeiro"),
                        ],
                        default="ADVOGADO",
                        max_length=20,
                    ),
                ),
                (
                    "oab",
                    models.CharField(blank=True, max_length=30, verbose_name="OAB"),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Acesso ativo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis / Acessos",
            },
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Número do processo (CNJ)",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="Título / Identificação"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("CIVEL", "Cível"),
                            ("TRABALHISTA", "Trabalhista"),
                            ("CRIMINAL", "Criminal"),
                            ("TRIBUTARIO", "Tributário"),
                            ("FAMILIA", "Família e Sucessões"),
                            ("PREVIDENCIARIO", "Previdenciário"),
                            ("CONSUMIDOR", "Consumidor"),
                            ("EMPRESARIAL", "Empresarial"),
                            ("OUTRO", "Outro"),
                        ],
                        default="CIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tipo de ação"
                    ),
                ),
                ("parte_contraria", models.CharField(blank=True, max_length=255)),
                (
                    "vara",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Vara / Órgão"
                    ),
                ),
                (
                    "comarca",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Comarca / Foro"
                    ),
                ),
                ("tribunal", models.CharField(blank=True, max_length=255)),
                (
                    "instancia",
                    models.CharField(
                        choices=[
                            ("1", "1ª Instância"),
                            ("2", "2ª Instância"),
                            ("SUP", "Tribunais Superiores"),
                        ],
                        default="1",
                        max_length=3,
                    ),
                ),
                (
                    "valor_causa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor da causa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANDAMENTO", "Em andamento"),
                            ("SUSPENSO", "Suspenso"),
                            ("ARQUIVADO", "Arquivado"),
                            ("ENCERRADO", "Encerrado"),
                        ],
                        default="ANDAMENTO",
                        max_length=12,
                    ),
                ),
                (
                    "data_distribuicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de distribuição"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Prazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("data_fatal", models.DateField(verbose_name="Data fatal")),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CUMPRIDO", "Cumprido"),
                            ("PERDIDO", "Perdido"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prazos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prazos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prazos",
                        to="gestao.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prazo",
                "verbose_name_plural": "Prazos",
                "ordering": ["data_fatal"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="gestao.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("RECEITA", "Receita"), ("DESPESA", "Despesa")],
                        default="RECEITA",
                        max_length=8,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("HONORARIOS", "Honorários"),
                            ("CUSTAS", "Custas processuais"),
                            ("REEMBOLSO", "Reembolso"),
                            ("SALARIO", "Salário / Pró-labore"),
                            ("ALUGUEL", "Aluguel"),
                            ("FORNECEDOR", "Fornecedor"),
                            ("IMPOSTO", "Imposto / Tributo"),
                            ("OUTRO", "Outro"),
                        ],
                        default="HONORARIOS",
                        max_length=12,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("data_vencimento", models.DateField(verbose_name="Vencimento")),
                (
                    "data_pagamento",
                    models.DateField(blank=True, null=True, verbose_name="Pagamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago / Recebido"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="gestao.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento financeiro",
                "verbose_name_plural": "Lançamentos financeiros",
                "ordering": ["-data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="Compromisso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REUNIAO", "Reunião"),
                            ("ATENDIMENTO", "Atendimento"),
                            ("DILIGENCIA", "Diligência"),
                            ("OUTRO", "Outro"),
                        ],
                        default="REUNIAO",
                        max_length=12,
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                (
                    "fim",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim"),
                ),
                ("local", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compromissos",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compromissos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compromissos",
                        to="gestao.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromisso",
                "verbose_name_plural": "Compromissos",
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="Audiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONCILIACAO", "Conciliação / Mediação"),
                            ("INSTRUCAO", "Instrução e Julgamento"),
                            ("UNA", "Una"),
                            ("PRELIMINAR", "Preliminar"),
                            ("OUTRA", "Outra"),
                        ],
                        default="CONCILIACAO",
                        max_length=12,
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="Data e hora")),
                ("local", models.CharField(blank=True, max_length=255)),
                (
                    "link_virtual",
                    models.URLField(
                        blank=True, verbose_name="Link (audiência virtual)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                            ("ADIADA", "Adiada"),
                        ],
                        default="AGENDADA",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audiencias",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audiencias_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiencias",
                        to="gestao.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audiência",
                "verbose_name_plural": "Audiências",
                "ordering": ["data_hora"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AFAZER", "A fazer"),
                            ("FAZENDO", "Em andamento"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="AFAZER",
                        max_length=10,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=6,
                    ),
                ),
                (
                    "prazo",
                    models.DateField(blank=True, null=True, verbose_name="Prazo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="gestao.processo",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
