# Generated by Django 6.0.1 on 2026-07-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_solicitacaoassinatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('DJEN', 'Publicação DJEN'), ('GMAIL', 'Gmail'), ('AGENDA', 'Google Agenda'),
                    ('DRIVE', 'Google Drive'), ('PRAZO', 'Prazo'), ('AUDIENCIA', 'Audiência'),
                    ('SISTEMA', 'Sistema'),
                ],
                default='SISTEMA', max_length=12,
            ),
        ),
        migrations.CreateModel(
            name='ArquivoGoogleDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_externo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('caminho', models.CharField(blank=True, max_length=2000)),
                ('link', models.URLField(blank=True)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_md5', models.CharField(blank=True, max_length=32)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='arquivos_google_drive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo Google Drive',
                'verbose_name_plural': 'Arquivos Google Drive',
                'ordering': ['caminho', 'nome'],
                'constraints': [models.UniqueConstraint(
                    fields=('user', 'identificador_externo'),
                    name='arquivo_drive_usuario_identificador_unico',
                )],
            },
        ),
    ]
