# Generated by Django 6.0.1 on 2026-07-26 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_notificacao_tipo_arquivogoogledrive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagemJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('DATAJUD', 'DataJud'), ('DJEN', 'DJEN'), ('GMAIL', 'Gmail'), ('AGENDA', 'Google Agenda')], max_length=10)),
                ('identificador_origem', models.CharField(max_length=255)),
                ('titulo_origem', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('SENTENCA', 'Sentença'), ('INTIMACAO', 'Intimação'), ('AUDIENCIA', 'Audiência'), ('PRAZO', 'Prazo'), ('RECURSO', 'Recurso'), ('JUNTADA', 'Mera juntada'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('resumo', models.TextField(blank=True)),
                ('providencia_sugerida', models.TextField(blank=True)),
                ('confianca', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('requer_conferencia', models.BooleanField(default=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Triagem jurídica',
                'verbose_name_plural': 'Triagens jurídicas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='chave_unica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['user', 'chave_unica'], name='gestao_noti_user_id_49982c_idx'),
        ),
        migrations.AddField(
            model_name='triagemjuridica',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_juridicas', to='gestao.processo'),
        ),
        migrations.AddField(
            model_name='triagemjuridica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens_juridicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='triagemjuridica',
            index=models.Index(fields=['user', '-criado_em'], name='gestao_tria_user_id_012cec_idx'),
        ),
        migrations.AddConstraint(
            model_name='triagemjuridica',
            constraint=models.UniqueConstraint(fields=('user', 'fonte', 'identificador_origem'), name='triagem_usuario_fonte_origem_unica'),
        ),
    ]
