# Generated by Django 6.0.1 on 2026-07-26 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_triagemjuridica_notificacao_chave_unica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(fields=('user', 'chave_unica'), name='notificacao_usuario_chave_unica'),
        ),
    ]
