# Generated by Django 6.0.1 on 2026-07-26 02:54

from django.db import migrations, models


def adicionar_colunas_se_necessario(apps, schema_editor):
    """Compatibiliza bancos locais antigos que já receberam essas colunas."""
    tabela = 'gestao_prazo'
    existentes = {col.name for col in schema_editor.connection.introspection.get_table_description(
        schema_editor.connection.cursor(), tabela
    )}
    if 'avisos_enviados' not in existentes:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute("ALTER TABLE gestao_prazo ADD COLUMN avisos_enviados jsonb NOT NULL DEFAULT '[]'::jsonb")
        else:
            schema_editor.execute("ALTER TABLE gestao_prazo ADD COLUMN avisos_enviados text NOT NULL DEFAULT '[]'")
    if 'confirmado_em' not in existentes:
        tipo = 'timestamp with time zone' if schema_editor.connection.vendor == 'postgresql' else 'datetime'
        schema_editor.execute(f"ALTER TABLE gestao_prazo ADD COLUMN confirmado_em {tipo} NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_notificacao_notificacao_usuario_chave_unica'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(adicionar_colunas_se_necessario, migrations.RunPython.noop)],
            state_operations=[
                migrations.AddField(model_name='prazo', name='avisos_enviados', field=models.JSONField(blank=True, default=list)),
                migrations.AddField(model_name='prazo', name='confirmado_em', field=models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
