# Generated by Django 6.0.1 on 2026-07-28 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_prazo_termo_inicial_feriado_forense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoSincronizacaoDJEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=10)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_sincronizacao_djen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de sincronização DJEN',
                'verbose_name_plural': 'Solicitações de sincronização DJEN',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='gestao_soli_status_41c9e1_idx')],
            },
        ),
    ]
